version: "3"
services:
  mysql:
    image: mysql/mysql-server:8.0
    command: ["--bind-address=0.0.0.0"]
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile-development
    environment:
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/app
      - perfect_ruby_on_rails_development_bundle:/app/vendor/bundle
      - perfect_ruby_on_rails_development_node_modules:/app/node_modules

volumes:
  mysql-data:
    driver: local
  perfect_ruby_on_rails_development_bundle:
    driver: local
  perfect_ruby_on_rails_development_node_modules:
    driver: local
