default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  timeout: 5000
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] %>
  port: <%= ENV["MYSQL_PORT"] %>

development:
  <<: *default
  database: perfect_ruby_on_rails_development

test:
  <<: *default
  database: perfect_ruby_on_rails_test

production:
  <<: *default
  database: perfect_ruby_on_rails_production
